# Generated by Django 4.2.27 on 2026-02-02 21:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor'), ('journalist', 'Journalist')], default='reader', help_text="User's role in the system", max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('subscribed_journalists', models.ManyToManyField(blank=True, help_text='Journalists this reader is subscribed to', limit_choices_to={'role': 'journalist'}, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Publisher organization name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the publisher')),
                ('website', models.URLField(blank=True, help_text="Publisher's website URL")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the publisher was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the publisher was last updated')),
                ('editors', models.ManyToManyField(blank=True, help_text='Editors working for this publisher', limit_choices_to={'role': 'editor'}, related_name='publisher_editors', to=settings.AUTH_USER_MODEL)),
                ('journalists', models.ManyToManyField(blank=True, help_text='Journalists working for this publisher', limit_choices_to={'role': 'journalist'}, related_name='publisher_journalists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=300)),
                ('content', models.TextField(help_text='Article content/body')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the article was last updated')),
                ('approved', models.BooleanField(default=False, help_text='Whether the article has been approved for publishing')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the article was approved', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Editor who approved the article', limit_choices_to={'role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, help_text='Journalist author (for independent articles)', limit_choices_to={'role': 'journalist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, help_text='Publisher (for publisher content)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.publisher')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, help_text='Publishers this reader is subscribed to', related_name='subscribers', to='news.publisher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Newsletter title', max_length=300)),
                ('description', models.TextField(help_text='Newsletter description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the newsletter was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the newsletter was last updated')),
                ('articles', models.ManyToManyField(blank=True, help_text='Articles included in this newsletter', related_name='newsletters', to='news.article')),
                ('author', models.ForeignKey(help_text='Journalist who created this newsletter', limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_newsle_created_d9ffec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='news_articl_created_a034b3_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['approved'], name='news_articl_approve_79cbd7_idx'),
        ),
    ]
